import type {
  HabitTodayResponse,
  CategoryResponse,
  PowerResponse,
  CheckHabitResponse,
  AttributeDetail,
} from '../../types';

// -- Mock Categories --
export const mockCategories: CategoryResponse[] = [
  {
    id: 'cat-1',
    name: 'Training',
    color_code: '#ef4444',
    icon: '🏋️',
    sort_order: 1,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat-2',
    name: 'Study',
    color_code: '#3b82f6',
    icon: '📚',
    sort_order: 2,
    created_at: '2026-01-01T00:00:00Z',
  },
];

// -- Mock Habits --
export const mockHabits: HabitTodayResponse[] = [
  {
    id: 'habit-1',
    title: 'Push-ups',
    description: '100 push-ups daily',
    icon_emoji: '💪',
    importance: 'critical',
    attribute: 'str',
    frequency: 'daily',
    custom_days: null,
    target_time: null,
    is_temporary: false,
    start_date: '2026-01-01',
    end_date: null,
    sort_order: 1,
    is_active: true,
    category_id: 'cat-1',
    created_at: '2026-01-01T00:00:00Z',
    completed: true,
    streak_current: 5,
    streak_best: 12,
  },
  {
    id: 'habit-2',
    title: 'Meditation',
    description: '20 min meditation',
    icon_emoji: '🧘',
    importance: 'important',
    attribute: 'ki',
    frequency: 'daily',
    custom_days: null,
    target_time: null,
    is_temporary: false,
    start_date: '2026-01-01',
    end_date: null,
    sort_order: 2,
    is_active: true,
    category_id: 'cat-1',
    created_at: '2026-01-01T00:00:00Z',
    completed: false,
    streak_current: 3,
    streak_best: 7,
  },
  {
    id: 'habit-3',
    title: 'Read 30 pages',
    description: null,
    icon_emoji: '📖',
    importance: 'normal',
    attribute: 'int',
    frequency: 'daily',
    custom_days: null,
    target_time: null,
    is_temporary: false,
    start_date: '2026-01-01',
    end_date: null,
    sort_order: 1,
    is_active: true,
    category_id: 'cat-2',
    created_at: '2026-01-01T00:00:00Z',
    completed: false,
    streak_current: 0,
    streak_best: 4,
  },
  {
    id: 'habit-4',
    title: 'Run 5km',
    description: null,
    icon_emoji: '🏃',
    importance: 'important',
    attribute: 'vit',
    frequency: 'weekdays',
    custom_days: null,
    target_time: null,
    is_temporary: false,
    start_date: '2026-01-01',
    end_date: null,
    sort_order: 2,
    is_active: true,
    category_id: 'cat-1',
    created_at: '2026-01-01T00:00:00Z',
    completed: false,
    streak_current: 2,
    streak_best: 10,
  },
];

export const mockCheckedHabit = mockHabits[0]; // completed: true
export const mockUncheckedHabit = mockHabits[1]; // completed: false

// -- Mock Attributes --
export const mockAttributes: AttributeDetail[] = [
  {
    attribute: 'str',
    raw_xp: 1250,
    level: 5,
    title: 'Warrior',
    xp_for_current_level: 1000,
    xp_for_next_level: 1500,
    progress_percent: 50,
  },
  {
    attribute: 'vit',
    raw_xp: 800,
    level: 3,
    title: 'Runner',
    xp_for_current_level: 600,
    xp_for_next_level: 1000,
    progress_percent: 50,
  },
  {
    attribute: 'int',
    raw_xp: 2000,
    level: 7,
    title: 'Scholar',
    xp_for_current_level: 1800,
    xp_for_next_level: 2200,
    progress_percent: 50,
  },
  {
    attribute: 'ki',
    raw_xp: 600,
    level: 2,
    title: 'Novice',
    xp_for_current_level: 400,
    xp_for_next_level: 800,
    progress_percent: 50,
  },
];

// -- Mock Power Response --
export const mockPowerResponse: PowerResponse = {
  power_level: 5000,
  transformation: 'ssj',
  transformation_name: 'Super Saiyan',
  next_transformation: 'ssj2',
  next_threshold: 10000,
  dragon_balls_collected: 3,
  wishes_granted: 0,
  attributes: mockAttributes,
};

// -- Mock Check Response --
export const mockCheckResponse: CheckHabitResponse = {
  is_checking: true,
  habit_id: 'habit-2',
  log_date: '2026-03-05',
  attribute_xp_awarded: 25,
  is_perfect_day: false,
  zenkai_activated: false,
  daily_log: {
    habits_due: 4,
    habits_completed: 2,
    completion_rate: 50,
    completion_tier: 'kaioken_x3',
    xp_earned: 25,
    streak_multiplier: 1.0,
    zenkai_bonus_applied: false,
    dragon_ball_earned: false,
  },
  streak: { current_streak: 3, best_streak: 7 },
  habit_streak: { current_streak: 4, best_streak: 7 },
  power_level: 5025,
  transformation: 'ssj',
  transform_change: null,
  dragon_ball: null,
  capsule: null,
  quote: {
    character: 'Goku',
    quote_text: 'I am the hope of the universe!',
    source_saga: 'Frieza Saga',
    avatar_path: '/assets/avatars/goku.webp',
  },
};
